---
title: "Satispay partners with Mastercard for debit cards"
date: 2026-07-08
retrieved: 2026-07-08
tags:
  - company/satispay
  - company/mastercard
  - industry/cards
  - region/europe
  - type/partnership
sources:
  - https://newsletter.thepaypers.com/i/7X0ftpGaXF1zz9WVwGK1I5qcdbSwXVZYrjL6khLKLx5MjmfZ2SiBiNDVlw-ujF7KPmX94-wLkLZvMr5KFrwAmSMfuYXw3aq8sGDGz0b5gZvyhp7Mcqh8SjHrDu4uisX1p8mHSC1EMkCVhit7NN-eCGB5RUEL_CNQ4W_SIhaMc1g
status: published
n_mentions: 1
channels:
  - "The Paypers"
story_id: sd35ed23c
month: 2026-07
enriched: true
importance: 4
freshness: fresh
---

# Satispay partners with Mastercard for debit cards

> [!info] 2026-07-08 · 1 упоминаний · 1 источника(ов) с текстом
> Каналы: The Paypers

## Агрегированный текст (из дайджестов)

[The Paypers] Satispay partners with Mastercard for debit cards

## Первоисточники

### newsletter.thepaypers.com
<https://newsletter.thepaypers.com/i/7X0ftpGaXF1zz9WVwGK1I5qcdbSwXVZYrjL6khLKLx5MjmfZ2SiBiNDVlw-ujF7KPmX94-wLkLZvMr5KFrwAmSMfuYXw3aq8sGDGz0b5gZvyhp7Mcqh8SjHrDu4uisX1p8mHSC1EMkCVhit7NN-eCGB5RUEL_CNQ4W_SIhaMc1g>
*761 слов · direct*

Satispay partners with Mastercard for debit cards
Sinziana Albu
08 Jul 2026 / 5 Min Read
Italy-based Satispay has partnered with Mastercard to launch debit cards and introduced in-app stock and ETF trading for its users.
The move follows the rollout of IBAN accounts earlier in 2026 and marks a further step in the company's expansion into broader banking services. The launch comes after a recent capital increase and takes the platform's user base, which stands at 6.5 million, alongside 450.000 affiliated merchants, into a new phase of product development.
Debit card offering
According to the official press release, the new cards will allow Satispay users to make payments globally, extending the service beyond the network of merchants that currently accept the app's proprietary payment method. The offering includes three physical debit cards, each linked to a different Satispay subscription tier and issued on the Mastercard circuit.
The entry-level card, included in the Satispay Plus plan, is a Mastercard Platinum card made of recycled PVC, offering double loyalty points, insurance coverage on online and in-store purchases, and preferential terms on top-ups, savings and investment products, and it is expected to become available without a subscription plan in the coming months. The Satispay Metal card, a metal Mastercard World card aimed at frequent travellers, includes no foreign exchange fees on non-euro transactions, higher free withdrawal limits, discounted airport lounge access and extended insurance cover, alongside triple loyalty points. At the same time, the Satispay Velvet card, a Mastercard World Elite product, offers unlimited free airport lounge access, no foreign exchange fees, the highest withdrawal limits in the range and quadruple loyalty points. All three cards will also be issued in digital form for mobile wallets. The offering is expected to reach the full user base within the coming days.
Stock and ETF trading
Alongside the card launch, Satispay has expanded its investment offering, which already counts half a million users, with a new in-app service for buying and selling stocks and ETFs, expected to go live the following week. The service gives users access to more than 1.000 stocks and ETFs, with a fixed fee of EUR 0.89 per trade and free recurring investment plans on selected Vanguard ETFs. Fractional shares allow users to begin investing with as little as EUR 1.
The service adds to Satispay's existing investment products, which include a remunerated savings account and mutual funds, and follows a broader trend among European payment apps of bundling banking, payments and investment features within a single platform.
Market context
The partnership with Mastercard gives Satispay access to a global card acceptance network, addressing a limitation of its proprietary payment circuit, which has previously been used mainly for domestic transactions and merchant payments in Italy. For Mastercard, the agreement extends its card issuing business into the fintech segment in Italy, where Satispay has built a large domestic user base. The combined rollout of card issuance and investment services reflects an ongoing shift among payment apps toward offering a fuller range of banking functions, as providers compete for a larger share of users' everyday financial activity.
 News on Fintech
Satispay partners with Mastercard for debit cards
GoTyme receives fresh USD 13.9 mln capital injection
Toss reportedly postpones US Nasdaq listing plan
Kraken to pursue European banking licence via Lithuania
Yapily brings bank account verification to Google Cloud in Europe
 Expert views on Fintech
What's the best career advice you've ever received? We asked the leaders shaping payments and fintech.
Agentic commerce does not threaten the rails. It threatens the toll.
The Quantum Column: Quantum computing in banking
The SAASpocalypse and payments: who survives when the per-seat model dies?
Digital payment networks in 2026: bubble, or business infrastructure?
 The Paypers is a global hub for market insights, real-time news, expert interviews, and in-depth analyses and resources across payments, fintech, and the digital economy. We deliver reports, webinars, and commentary on key topics, including regulation, real-time payments, cross-border payments and ecommerce, digital identity, payment innovation and infrastructure, Open Banking, Embedded Finance, crypto, fraud and financial crime prevention, and more – all developed in collaboration with industry experts and leaders. 
Categories
 Payments 
 Fraud and Fincrime 
 Fintech 
 Crypto, Web3 and CBDC 
 Regulations 
 M&A and Investments 
Current themes
 A2A Payments 
 Payment Orchestration 
 TradFi and DeFi Convergence 
 KYC, KYB and Digital Identity 
 Scams and Fraud 
 Embedded Finance 
 Real-Time Payments 
The Paypers
 Team 
 Advertise 
 About 
Contact
The Paypers
Prinsengracht 777e 
1017 JZ Amsterdam
P: +31 20 658 0652
No part of this site can be reproduced without explicit permission of The Paypers (v2.7).
 Privacy Policy  / Cookie Statement 
Copyright

## Контекст

<!-- enrichment:context -->
# Context-enrichment: Satispay partners with Mastercard for debit cards
_Analytical notes (not a post). Importance: 4/5._

## [0] What exactly happened (de-PR'd)
Satispay (Milan; Luxembourg EMI Satispay Europe S.A.) launched **three physical debit cards on the Mastercard circuit**, each gated behind a paid subscription tier, plus digital versions for mobile wallets. Announced ~7–8 Jul 2026, rolling to the 6.5M user base "within days" (digital cards immediately usable). This is Satispay's **first-ever scheme-branded card** — the company was historically built *explicitly card-network-free*.
- **The three cards (subscription-gated, upsell ladder):** *Red* = Mastercard Platinum (recycled PVC, in the Plus plan, 2x points, purchase insurance; to be offered without a plan "in coming months"); *Metal* = Mastercard World Debit (metal, travellers: 0% FX on non-EUR, higher free ATM limits, lounge discounts, 3x points); *Velvet* = Mastercard World Elite (unlimited lounges, 0% FX, highest limits, 4x points).
- **Bundled same-day with stock/ETF trading** — that is a *separate story* covered in [[Satispay partners Upvest to bring stocks to Italy, Luxembourg]] (Upvest is the securities-rail supplier). This note is strictly the **Mastercard card** leg.
- **Why structured this way (the tell):** Satispay's core network runs on **A2A / direct-IBAN, SEPA-settled** rails that *deliberately bypass Visa/Mastercard interchange* — that low-flat-fee model was the founding brand differentiator. Bolting on Mastercard is not a rail swap but an **admission that the proprietary QR circuit cannot deliver reach** (abroad, travel, e-commerce, any non-affiliated merchant). The PR frames it as "global acceptance"; de-PR'd, it means the domestic-only ceiling was real. The card is *additive* (spend where own rails don't reach), so it softens — but does not kill — the "we're cheaper, no card fees" pitch. It also monetises the premium tiers (Plus/Metal/Velvet) via subscriptions + outbound interchange.
- **Open:** issuing model unconfirmed — principal Mastercard issuer vs BIN sponsor / program manager unnamed. Own IBAN (H1 2026) + Lux EMI make in-house issuing plausible but not confirmed. Acquiring involvement, exclusivity/term also open.

## [1] Competitors / peers
- **The European A2A cohort making the same trade (reach beats rail-purity):** Wero/EPI (absorbed iDEAL, giropay, Paylib, Payconiq; interoperating with Bizum, Bancomat, MB Way, Vipps), with Revolut joining EPI (Jun 2025) and N26 integrating Wero. The whole pure-A2A generation is converging on hybrid A2A + card + super-app.
- **Direct super-app/neobank rivals:** Revolut, N26 — precisely the card+IBAN+savings+investing bundle Satispay now emulates.
- **Italy card landscape:** Bancomat/PagoBancomat (domestic debit scheme) and Nexi (dominant acquirer/processor); Satispay's issuing move nudges it toward card-issuer-adjacent territory. For Mastercard, this is a marquee fintech-issuing win in an under-digitised market.
- **Why this way (2nd order):** every A2A challenger eventually hits the same wall — a domestic-only proprietary net can't serve travel/e-comm/cross-border, so it either builds Wero-scale interop *or* rents Mastercard/Visa reach. Satispay chose the faster path (rent the rail). The cost: it re-enters the interchange economics it was built to avoid, and its differentiation narrows toward brand + distribution rather than "cheaper rails."

## [2] Company history / fit
Trajectory: proprietary A2A network (2015) → welfare (2023) → Remunerated Piggy Bank → 3 managed funds + Investments section (Jan 2026, Invesco/Amundi + Fondaco; [[Satispay launches three funds and new investment section]]) → Pay-in-3 BNPL ([[Satispay launches Pay in 3 BNPL for physical shops in Italy]]) → own IBAN (H1 2026) → pensions → self-directed stocks/ETFs + Mastercard cards (Jul 2026). Metrics (May–Jun 2026): **6.5M users, 450k+ merchants, €670M deposits (May), ARR ~€120M (+80% YoY), >500k investors**, valuation >€1B; backers Addition, Greyhound, Lightrock, Tencent, Block, Mediolanum. The **€120M capital increase** (approved 29 Jun 2026; [[Satispay approves capital increase of up to €120 million]]) was explicitly earmarked to fund exactly this "payment app → full financial platform" push.
- **Why (structural pressure):** a bank-to-bank payment network is a low-margin, low-multiple business. To justify a >€1B software-style valuation Satispay must stack higher-value banking products onto its captive Italian base — cards deepen wallet-share, add interchange revenue, and are table-stakes for a "primary account" claim. IBAN → cards → investing is the standard neobank ladder; the move is **on-strategy, not a pivot**.

## [3] Novelty / value-add / traction
- **Genuinely new for Satispay:** first card-network product ever, from a company that defined itself *against* card rails. That reversal is the story — not the (commoditised) act of issuing a Mastercard debit card, which hundreds of fintechs do.
- **Traction = zero at announce:** cards are announced/rolling, not adopted. No usage, activation, or interchange figures. Treat as **launch, not adoption**; premium-tier attach rate is the real KPI and is unknown (open).
- **Who captures the margin (2nd order):** on card spend, Mastercard takes scheme fees and the issuing/interchange stack is thin for a small issuer; the *durable* value for Satispay is **subscription revenue** (Plus/Metal/Velvet tiers) + stickiness, not interchange. The strategic value-add is real (removes the reach ceiling, enables "primary account" positioning); the P&L value-add is **incremental**, not transformative.

## [4] What's next / market sentiment
- **Plans:** extend entry card beyond subscription "in coming months"; full super-app (cards + IBAN + savings + stocks/ETFs + pensions). €120M raise funds organic growth (~50% pre-committed by Greyhound/Addition/Lightrock) + optional M&A.
- **Sentiment / caution (analysis):** valuation has been **flat since the Sep 2022 €320M Series D** (~4 years); one analysis frames the €120M as "runway extension at a flat valuation" rather than growth capital — a soft-momentum signal. Germany appears deprioritised/wound back (open on formal exit); footprint effectively Italy-core + France (Nice) + Lux HQ.
- **Why the market goes this way / counterintuitive 2nd order:** the "no card fees" A2A pitch was Satispay's moat *and* its cage. Adopting Mastercard buys reach but **commoditises the offering toward Revolut/N26**, where Satispay competes on Italian distribution/trust — a real asset, but one that yields a thin investing/card take-rate. The central question shifts from *"can A2A scale a super-app?"* to *"once it rents card + securities rails, what does Satispay still own besides the Italian customer relationship?"*

## Sources
- The Paypers (primary, in-note): Satispay partners with Mastercard for debit cards, 08 Jul 2026.
- Satispay newsroom: <https://www.satispay.com/it-it/newsroom/satispay-carte-di-debito-mastercard/>
- Finextra: <https://www.finextra.com/newsarticle/48051/italian-fintech-satispay-partners-mastercard-for-debit-card-launch>
- EU-Startups (June 2026 €120M raise): <https://www.eu-startups.com/2026/06/italian-fintech-unicorn-satispay-plans-e120-million-raise-secures-nearly-e60-million-from-existing-investors/>
- TechCrunch (Series D 2022): <https://techcrunch.com/2022/09/28/italys-satispay-raises-e320m-at-a-e1b-valuation-with-backing-from-block-tencent-and-more-for-its-indy-payment-network/>
- Il Sole 24 Ore (capital increase): <https://en.ilsole24ore.com/art/satispay-capital-increase-of-up-to-120-million-AIpOnfbD>
- Wero/EPI context: <https://en.wikipedia.org/wiki/Wero_(payment)>
<!-- /enrichment:context -->

## Челлендж / ред-тим

<!-- enrichment:challenge -->
## Top challenge / red-team questions (second-order)

1. **Is Satispay a principal Mastercard issuer or riding a BIN sponsor / program manager?** — Open. Not disclosed. Lux EMI + own IBAN (H1 2026) make in-house issuing plausible but unconfirmed. Determines who owns the card economics.
2. **Live or just announced?** — Announced ~7–8 Jul 2026; digital cards immediately usable, physical "within days." Launch/phased rollout — **no adoption data**.
3. **What is the durable revenue here — interchange or subscriptions?** — Subscriptions (Plus/Metal/Velvet tiers), not interchange. For a small issuer the interchange stack is thin; premium-tier attach rate is the real KPI (unknown).
4. **Does this abandon the low-fee A2A model that was the whole differentiator?** — No; cards are additive (abroad/online/off-circuit). But it **softens the "no card fees" pitch** and pushes Satispay toward Revolut/N26 parity.
5. **What does Satispay still own once it rents both card rails (Mastercard) and securities rails (Upvest)?** — Mainly the Italian customer relationship + daily-payments habit. That is real distribution but a thin take-rate — this reframes the central question of the whole thesis.
6. **Is the >€1B valuation real / current?** — Reaffirmed by the June 2026 raise but **flat since Sep 2022** (~4 yrs). One analysis calls the €120M a "runway extension at flat valuation." Soft-momentum flag.
7. **Geography of the card at launch — Italy only or FR/LU too?** — Primary rollout to the Italy-heavy 6.5M base; acceptance is global but per-country card availability (France/Lux) is **open**.
8. **Did Satispay exit Germany?** — Coverage shifts focus to IT/FR/LU; **formal exit unconfirmed (open)**. Signals retrenchment to a defensible core.
9. **Are the cards free or subscription-gated?** — Gated: Red = Plus plan; Metal/Velvet = higher paid tiers. Entry card to go plan-free "in coming months."
10. **Does adding cards cannibalise Satispay's low-fee merchant model?** — Card spend is largely incremental (out-of-network/abroad), so likely net-additive; but it dilutes the brand narrative more than the P&L.
11. **Prior card issuance or prior Visa/Mastercard tie-up?** — None found. This is the first scheme card — that reversal is the actual news, not the (commoditised) product.
12. **Is there acquiring (merchant-side) in the deal, or issuing only?** — Sources describe consumer-debit **issuing only**; acquiring/exclusivity/term all **open**.
13. **How does this compare to the European A2A cohort (Wero/EPI)?** — Same trade — reach beats rail-purity. Wero builds interop; Satispay rents Mastercard. Faster path, higher long-run fee cost.
14. **Is "€120M ARR" revenue or run-rate?** — ARR (~€116M at 31 May 2026, ~€120M by June), +80% YoY. Recurring run-rate, not audited annual revenue.
15. **What breaks the thesis?** — Low premium-tier attach + commoditisation vs Revolut/N26 + flat valuation → Satispay becomes "Italian distribution over rented rails" with a thin take-rate rather than a rail owner.

Importance: 4/5 — A genuinely strategic reversal: Italy's flagship A2A challenger, long defined by *avoiding* card rails, embraces Mastercard — a clear signal pure A2A can't deliver the reach needed to become a super-app, mirroring the pan-European A2A→hybrid convergence (Wero, Revolut/N26). Not 5 because it's a single-market issuing launch with zero adoption data, flat valuation since 2022, and card economics that are incremental to the P&L rather than transformative.
<!-- /enrichment:challenge -->

## Связь с постом

<!-- enrichment:post -->
Опубликовано в дайджесте [[digest/2026-07-09]] (2026-07-09).
<!-- /enrichment:post -->

## Market Research

<!-- enrichment:market_research -->
**Sector & drivers.** Satispay sits at the A2A-vs-card fault line in European payments. A2A/pay-by-bank made ~17% of European e-commerce transaction value in 2024 and is forecast to exceed €850bn in transaction value by 2026, with volumes growing ~30% in 2025 (per secondary analyst/press aggregation, via banking.vision / europeanbusinessmagazine.com, as of 2026). Structurally the space is **bifurcating**: (a) sovereign A2A interop — Wero/EPI + the Feb-2026 EPI-EuroPA agreement links Wero, Bizum, Bancomat, MB Way, Vipps into ~130M users / 13 countries (~72% of EU population, per trendingtopics.eu/philippdubach.com); (b) the global card duopoly (Visa/Mastercard) that still owns cross-border, travel and any non-domestic merchant. "Why now": every domestic A2A champion hits a reach ceiling and must either build interop (Wero) or **rent** card rails — Satispay just chose the rent path. Barriers are network effects (two-sided merchant/user) + regulation (EMI/IBAN licensing); value in cards accrues to the scheme + issuing/processing stack, not the app. (analysis)

**Competitive landscape.** Sector KPIs: TPV/GPV, take rate, per-transaction margin, and — for the neobank layer Satispay is entering — ARPU, premium-tier attach rate, price-per-user. Key players & basis of competition: **Revolut / N26** (product breadth + card+IBAN+investing bundle — exactly what Satispay now emulates); **Wero/EPI** (interop, rail-purity, sovereignty pitch); **Bizum** (30M+ users, ~3.4M daily tx, going in-store 2026 — the Spanish mirror of Satispay's Italian position); domestically **Bancomat/PagoBancomat** + **Nexi** (Italy acquiring/processing incumbent). Recent moves: Revolut $75bn round + 75M customers, targeting ~$9bn 2026e revenue (Fortune, 03 Jul 2026); Wero POS rollout across DE/BE/NL/FR/LU through 2026. Satispay's position: **domestic leader, sub-scale pan-EU niche** — 6.5M users / 450k merchants vs Revolut's 75M. Its moat is Italian distribution + daily-payment habit + merchant density (real switching costs locally), NOT rails — which it now rents from both Mastercard (cards) and Upvest (securities). (analysis)

**Comps & multiples.** Price-per-user (round/last valuation ÷ users) and value/ARR:
| Co | Valuation | Users | €/user | Rev proxy | Val/Rev |
|---|---|---|---|---|---|
| Satispay | >€1bn (flat since Sep-2022 Series D) | 6.5M | €1bn/6.5M ≈ **€154** | €116M ARR (31 May) | 1000/116 ≈ **8.6x** |
| Revolut | $75bn (2026) | 75M | 75bn/75M = **$1,000** | ~$9bn 2026e | 75/9 ≈ **8.3x** |
| N26 | $6bn | 4.8M | 6bn/4.8M ≈ **$1,250** | €440M ('24, ≈$0.48bn) | 6/0.48 ≈ **12.6x** |

Satispay is a **~6–8x cheaper per user** than Revolut/N26 (€154 vs $1,000–1,250) — consistent with (a) a single-market, lower-ARPU, still-thin monetisation base, and (b) a **valuation flat for ~4 years** while peers re-rated. On Val/ARR it prints ~8.6x, in-line with Revolut (~8.3x) and below N26 (~12.6x) — but the per-user gap says the market treats Satispay as *domestic distribution*, not a global neobank. Internal comps: [[Satispay approves capital increase of up to €120 million]] (flat-round runway), [[Satispay launches three funds and new investment section]] and [[Satispay partners Upvest to bring stocks to Italy, Luxembourg]] (super-app ladder), [[Satispay launches Pay in 3 BNPL for physical shops in Italy]]; Mastercard-issuing precedents [[Australia's Vault becomes Mastercard Principal Issuer]], [[Kraken launches Mastercard for UK and European users]]. Multiples are on **private round valuations / ARR run-rate**, not audited market caps — treat as indicative, not clean.

**Counterparty scale (Mastercard, EDGAR-grounded):** Q1 2026 net revenue **$8.4bn, +16% YoY**; net income **$3.9bn (+18%)**; VAS net revenue +22%; cross-border volume +13% (10-Q filed 30 Apr 2026, EDGAR; Mastercard Q1'26 earnings release). For Mastercard the Satispay deal is immaterial to the P&L but a marquee **fintech-issuing win in an under-carded Italian market** — it extends card rails precisely into the A2A challenger camp.

**Risk flags.**
1. **Margin/model dilution (interchange re-entry).** Satispay was built *against* card interchange; bolting on Mastercard re-imports scheme + issuing economics it once avoided. For a small issuer the interchange stack is thin, so the *durable* revenue is subscriptions (Plus/Metal/Velvet), not interchange — if premium-tier attach is low, the P&L benefit is marginal while brand differentiation ("no card fees") erodes. Second-order: convergence toward Revolut/N26 on product but at ~6–8x lower per-user value.
2. **Geographic concentration + flat valuation.** ~Italy-core (FR/LU thin, Germany apparently wound back), 6.5M users vs Revolut's 75M, and a valuation **flat since 2022**. One analysis (ainvest.com) frames the €120M as "runway extension at a flat valuation." A single-market challenger renting global rails has limited pricing power to justify re-rating.
3. **Disintermediation of its own moat / execution.** Once it rents both card rails (Mastercard) and securities rails (Upvest), what Satispay *owns* narrows to the Italian customer relationship — a real but thin-take-rate asset. Execution risk on simultaneously shipping cards + self-directed trading + IBAN to 6.5M users with zero adoption data at announce.

**What this changes (idea-lens).** This is the clearest single-name marker of the pan-European A2A→hybrid convergence: the flagship "card-free" challenger conceding that pure A2A can't build a super-app alone (analysis). Falsifiable thesis: if premium-tier (Metal/Velvet) attach + card TPV don't move ARR materially above the +80% trend within ~2–3 quarters, Satispay re-rates *down* toward "Italian distribution over rented rails," not up toward a neobank multiple. Trigger to watch: first disclosed card activation / premium-attach metrics and any 2026 up-round (or another flat one). Wero POS go-live (H2 2026) is the sovereignty-path counterfactual to Satispay's rent-the-rail bet.

Sources: https://www.stocktitan.net/sec-filings/MA/10-q-mastercard-inc-quarterly-earnings-report-0db7b6eecfe5.html · https://www.sec.gov/Archives/edgar/data/1141391/000114139126000031/ma-20260331.htm · https://s25.q4cdn.com/479285134/files/doc_financials/2026/q1/1Q26-Mastercard-Earnings-Release.pdf · https://www.eu-startups.com/2026/06/italian-fintech-unicorn-satispay-plans-e120-million-raise-secures-nearly-e60-million-from-existing-investors/ · https://www.ainvest.com/news/satispay-120m-funding-growth-capital-runway-extension-2606/ · https://fortune.com/2026/07/03/75-billion-valuation-london-america-ipo-francesca-carlesi/ · https://sacra.com/c/n26/ · https://www.trendingtopics.eu/europes-players-unite-to-challenge-visa-mastercard-and-paypal-with-shared-payment-network/ · https://banking.vision/en/development-wero-2025-2026/
<!-- /enrichment:market_research -->

## Earnings Review

<!-- enrichment:earnings_review -->
**Verdict (headline read).** N/A — no earnings event. This is a product/partnership launch (first scheme-branded card), not a results print. Satispay is private with **no formal earnings release**; the only hard financials are company-reported operating metrics disclosed alongside the 29 Jun 2026 €120M capital increase. Counterparty Mastercard's latest actuals (Q1 2026) are strong but immaterial to this deal. Read: **operating momentum intact (ARR +80% YoY), monetisation still early, zero adoption data on the cards themselves.**

**Key figures (Satispay — company-reported, private, un-audited).**
- **ARR: €116M+ at 31 May 2026, +80% YoY** over the prior two quarters (self-reported, funding-round disclosure — this is annualised run-rate, NOT audited annual revenue). Third-party trackers cite ~$136.5M 2026 revenue, but the primary company figure is the €116M+ ARR.
- **Users: 6.5M** (vs 6.0M in Apr 2026 IR, 5.0M+ in late 2024) — steady mid-single-digit-monthly build.
- **Merchants: 450,000+** affiliated (vs 400k+ Apr 2026).
- **Deposits: €670M** (31 May 2026).
- **Investors: 500,000+ with €140M+ invested AUM**; the new in-app self-directed stock/ETF service (>1,000 instruments, €0.89/trade) layers onto this.
- **Welfare: €420M annualised volume at end-May 2026, +250% YoY.**
- **Valuation: >€1bn**, reaffirmed by the €120M raise but **flat since the Sep-2022 €320M Series D (~4 yrs)** — the key monetisation-vs-multiple tension.

**Key figures (Mastercard — scale context, EDGAR-grounded, Q1 2026, reported 30 Apr 2026).**
- Net revenue **$8.4bn, +16% reported / +12% currency-neutral YoY** (vs $7.3bn Q1'25).
- GAAP net income **$3.9bn, +18%**; GAAP diluted EPS **$4.35** (vs $3.73), **adjusted EPS $4.60 (+18% cn)**, beating consensus ~$4.41 by ~4.3%.
- **GDV $2.7tn, +7% LC**; **cross-border volume +13% LC**; **switched transactions +9% YoY**; **VAS net revenue +22% (+18% cn)**.
- $4.0bn buyback in Q1 + $1.7bn through 27 Apr 2026.
For Mastercard the Satispay deal is P&L-immaterial but a marquee **fintech-issuing win in an under-carded Italian market**.

**By segment / driver (Satispay).** Growth is being manufactured by **product-stacking on a captive Italian base**, not by geographic expansion: IBAN (H1'26) → BNPL → funds/investing → self-directed trading → now Mastercard cards. The card leg adds two monetisation vectors — **subscription tiers (Plus/Metal/Velvet)** and outbound **interchange** — but for a small issuer interchange is thin, so the durable driver is **premium-tier attach + wallet-share deepening**, which is the real (unknown) KPI. Welfare (+250%) and investing (500k+ investors) are the visible growth engines today; cards are additive spend where the proprietary QR circuit can't reach (abroad, e-comm, non-affiliated merchants).

**vs expectations / prior period.** No public consensus exists (private company; no analyst estimates). Qualitatively: ARR +80% YoY is a genuine acceleration vs a low-margin A2A-network base, and users/merchants/deposits all step up sequentially vs the Apr 2026 IR figures — trajectory is **up and to the right on operations**. But two prior-period flags: (1) **valuation flat ~4 years** while peers re-rated (Revolut $75bn, N26 $6bn); one analysis frames the €120M as "runway extension at a flat valuation." (2) On per-user value Satispay prints ~€154/user vs Revolut/N26 at ~$1,000–1,250 — a ~6–8x discount the market applies for single-market, thin-monetisation. Internal trend/corpus: [[Satispay approves capital increase of up to €120 million]], [[Satispay launches three funds and new investment section]], [[Satispay partners Upvest to bring stocks to Italy, Luxembourg]], [[Satispay launches Pay in 3 BNPL for physical shops in Italy]]; issuing precedents [[Australia's Vault becomes Mastercard Principal Issuer]], [[Kraken launches Mastercard for UK and European users]].

**Guidance / forward.** Satispay gives **no formal guidance** (private). Disclosed intent: extend the entry card beyond subscription "in coming months," complete the super-app (cards + IBAN + savings + stocks/ETFs + pensions); the €120M raise (~50% pre-committed by Greyhound/Addition/Lightrock) funds organic growth + optional M&A. Independent forecast (analysis): if the +80% ARR trend holds, run-rate crosses ~€200M within ~4–6 quarters — but the card launch adds **zero near-term revenue certainty** (announced, not adopted); the swing factor is premium-tier attach, unquantified. Mastercard's own guidance (context): Q2'26 net-revenue growth at the **low end of low-double-digits cn** (Middle East conflict the largest incremental headwind), FY26 maintained at the **high end of low-double-digits cn** (~1.5pt FX tailwind) — Mastercard's next print (Q2'26, ~end-July) is NOT yet out as of 08 Jul 2026.

**Thesis-flags.**
1. **No adoption data = launch, not traction.** Fact: cards announced/rolling, zero activation/interchange/attach figures → why: the entire economic case rests on premium-tier attach → why it matters: without attach, cards add cost (scheme fees, issuing) but little revenue → 2nd-order: the +80% ARR trend must be defended by welfare/investing, not cards, near-term.
2. **Interchange re-entry softens the founding moat.** Fact: a company built explicitly *against* card rails now issues Mastercard → why: proves the proprietary QR circuit couldn't deliver reach → why it matters: differentiation narrows toward Revolut/N26 parity → 2nd-order: Satispay competes on Italian distribution/trust (thin take-rate), not cheaper rails.
3. **Flat valuation vs accelerating ARR is the central tension.** Fact: >€1bn flat since 2022 while ARR +80% → why: market treats it as domestic distribution, not a global neobank → why it matters: an up-round (or another flat one) at next raise is the falsification trigger → 2nd-order: monetisation depth (ARPU, premium attach), not user count, is what re-rates it.
4. **Mastercard is scale context, not a P&L event.** For MA the deal is immaterial; for Satispay, Mastercard supplies reach + issuing rails but captures scheme fees — the durable Satispay value is subscriptions + stickiness, not the card economics themselves.

Sources: Satispay newsroom (€120M raise / ARR €116M+, +80% YoY, 6.5M users, 450k merchants, €670M deposits): https://www.satispay.com/it-it/newsroom/satispay-aumento-di-capitale-per-accelerare-la-crescita/ · EU-Startups (raise): https://www.eu-startups.com/2026/06/italian-fintech-unicorn-satispay-plans-e120-million-raise-secures-nearly-e60-million-from-existing-investors/ · beinsure (€116M ARR): https://beinsure.com/news/fintech-unicorn-satispay-plans-e120-mn-raise-after-e116-mn-arr/ · ainvest ("runway extension at flat valuation"): https://www.ainvest.com/news/satispay-120m-funding-growth-capital-runway-extension-2606/ · Mastercard Q1'26 release (EDGAR EX-99.1): https://www.sec.gov/Archives/edgar/data/1141391/000114139126000029/ma03312026-exx991xearnings.htm · Mastercard Q1'26 IR release PDF: https://s25.q4cdn.com/479285134/files/doc_financials/2026/q1/1Q26-Mastercard-Earnings-Release.pdf · Mastercard 10-Q (filed 30 Apr 2026): https://www.sec.gov/Archives/edgar/data/1141391/000114139126000031/ma-20260331.htm · Satispay-Mastercard launch (Finextra): https://www.finextra.com/newsarticle/48051/italian-fintech-satispay-partners-mastercard-for-debit-card-launch · No public Satispay consensus/estimates → [UNSOURCED for beat/miss]; Satispay operating figures are **company-reported, un-audited**; Mastercard Q2'26 not yet reported as of 08 Jul 2026 (no data).
<!-- /enrichment:earnings_review -->
